language: go
go:
  - 1.8.3

dist: trusty
sudo: false

before_install:
  - go get github.com/GetStream/vg
  - go get github.com/golang/dep/cmd/dep
  - 'eval "$(vg eval --shell bash)"'
  - vg init
  - go env

install:
  - make get-deps
  - make clean
  - make all
  - git diff --exit-code # Check if bindata file is up to date
