language: go
go:
  - 1.8.3

dist: trusty
sudo: false

before_install:
  - go get github.com/GetStream/vg
  - go get github.com/golang/dep/cmd/dep
  - 'eval "$(vg eval --shell bash)"'
  - vg init vg
  - echo $GOPATH
  - ls -al ~/.virtualgo || true

install:
  - make get-deps
  - make all
